apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.container.secretName }}
  namespace: {{ .Values.namespace | default "default" }}
type: Opaque
data:
  {{- range .Values.container.env.secret }}
  {{ .name }}: {{ .value | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.container.secretName2 }}
  namespace: {{ .Values.namespace | default "default" }}
type: Opaque
data:
  template.jinja: {{ .Files.Get (.Values.jinjaTemplatePath)| b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.container.secretName3 }}
  namespace: {{ .Values.namespace | default "default" }}
type: Opaque
data:
  xlam_tool_call_parser.py: {{ .Files.Get "files/xlam_tool_call_parser.py" | b64enc | quote }}
