---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: voicing-llm
  labels:
    app.kubernetes.io/name: voicing-llm
    app.kubernetes.io/instance: voicing-llm
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    iam.gke.io/gcp-service-account: kubernetes-pods@voicing-non-production.iam.gserviceaccount.com
automountServiceAccountToken: true
---
apiVersion: v1
kind: Service
metadata:
  name: voicing-llm
  labels:
    app.kubernetes.io/name: voicing-llm
    app.kubernetes.io/instance: voicing-llm
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: voicing-llm
    app.kubernetes.io/instance: voicing-llm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voicing-llm
  labels:
    app.kubernetes.io/name: voicing-llm
    app.kubernetes.io/instance: voicing-llm
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: voicing-llm
      app.kubernetes.io/instance: voicing-llm
  template:
    metadata:
      labels:
        app.kubernetes.io/name: voicing-llm
        app.kubernetes.io/instance: voicing-llm
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: voicing-llm
      containers:
        - name: toolace
          image: "vllm/vllm-openai:v0.8.5"
          command: ["/bin/sh","-c"]
          args: ["vllm serve voicing-ai/voicing-qwen3-30b-a3b-V2  --served-model-name voicing-llm-v1.5 --enable-auto-tool-choice --tool-call-parser hermes --load-format auto --dtype bfloat16 --gpu-memory-utilization 0.9 --max-num-batched-tokens 1024 --max-num-seq 1024 --max-model-len 65536 --disable-log-stats --tensor_parallel_size 1 --host 0.0.0.0 --port 8000"]
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token  
                  key: HUGGING_FACE_HUB_TOKEN            
          imagePullPolicy: Always
          stdin: true
          tty: true
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: "10"
              memory: 60Gi
              nvidia.com/gpu: "1"
            requests:
              cpu: "10"
              memory: 60Gi
              nvidia.com/gpu: "1"
          volumeMounts:
            - mountPath: /root/.cache/huggingface
              name: model-cache
      volumes:
        - emptyDir: {}
          name: model-cache
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-a100-80gb
---
